name: semif_prep
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - hydra-core
  - omegaconf
  - opencv
  - pandas
  - tqdm
  - piexif
  - pillow
  - reportlab
  - pip:
    - pexpect
    - requests
    - thop
    - tensorboard
    - shapely
    - exifread
    # TODO: add torch and torchvision and explicit Metashape install instructions
    # torch and torchvision
