name: semif_preprocessing
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - hydra-core
  - omegaconf
  - opencv
  - pandas
  - tqdm
  - pip:
    - opencv-python-headless  # Optional: for headless systems without GUI
    - piDNG