# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - override hydra/job_logging: custom
  
batch_id: NC_2025-01-13
tasks:
  # - copy_from_lockers
  - raw2dng

file_masks:
  raw_files:
    - .RAW
    - .raw


#copy_from_lockers:
#  raw_extension: .RAW # either .RAW or .ARW
  
job_now_date: &nowdir ${now:%Y-%m-%d}
