# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - dng_tags: default
  - ccm: NC_1740166530
  - preprocess_batches: test
  - override hydra/job_logging: custom
  
batch_id: NC_2025-02-21
tasks:
  - raw2jpg # raw2jpg does raw2dng + dng2jpg
  # - raw2dng
  # - dng2jpg
  # - inspect_images

rt_pp3_name: NC_2025-02-21
ccm_name: NC_1740166530

file_masks:
  raw_files:
    - .RAW
    - .raw
  dng_files:
    - .DNG
    - .dng
  png_files:
    - .png
    - .PNG
  
raw2jpg:
  jpg_samples: 50
  resize_factor: 0.25
  remove_dngs: true

max_workers: 16