# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - ccm: NC_1740166530
  - override hydra/job_logging: custom
  
batch_id: NC_2025-02-21
tasks:
#  - copy_from_lockers
  - raw2png
  - png2jpg

file_masks:
  raw_files:
    - .RAW
    - .raw
  dng_files:
    - .DNG
    - .dng
  png_files:
    - .png
    - .PNG

raw2png:
  height: 9528
  width: 13376
  bpp: 16
  remove_raws: false

png2jpg:
  rt_pp3_name: NC_2025-02-21
  remove_pngs: False

job_now_date: &nowdir ${now:%Y-%m-%d}

max_workers: 12
