# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - exif: default
  - asfm: default
  - date_ranges: default
  - override hydra/job_logging: custom

hydra:
  run:
    dir: ${paths.log_dir}/${season}/${batch_id}/${job_now}
  output_subdir: ${hydra.run.dir}/hydra

job_now: &nowdir ${now:%Y-%m-%d}/${now:%H:%M:%S}

############################################
# Main configuration for the current batch
############################################
batch_id: MD_2025-05-05
bbot_version: v3.1
season: cool_season_covers_2024_2025 # cool_season_covers_2024_2025, cool_season_covers_2024_2025_NCpos2, summer_weeds_2024
create_issue: true
gh_reviewer: mkutu # nnotaba or mkutu
timestamp: # epoch timestamp for raw2jpg. Anything before this timestamp will be ignored in the batch
run_mode: single # single or batch
modes:
  # - sync
  - correct
  - asfm
  - label
  - deliver
############################################

tasks: # task for each mode
  sync:
    - sync_from_remote # not implemented # TODO: create task list for sync
  correct:
    - raw2jpg # raw2jpg does raw2dng + dng2jpg
    - update_exif
  asfm:
    - autosfm # not implemented # TODO: create task list for autosfm
  label:
    - detect_plants
    - merge_overlapping_bboxes
    - remap_labels
    - assign_species
  deliver:
    - inspect_images # deliver
    - move_data # deliver
    - report  # deliver

inspection:
  inspect: false
  use_lts_images: false  # set true to inspect from LTS

rt_pp3_name: NC_2025-02-21
ccm_name:

file_masks:
  raw_files:
    - .RAW
    - .raw
  dng_files:
    - .DNG
    - .dng
  png_files:
    - .png
    - .PNG
  
raw2jpg:
  jpg_samples: 0
  resize_factor: 0.25
  remove_dngs: true

max_workers: 16


report:
  save2lts: true
  sample_size: 96 # best if this is a multiple of 12