# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - override hydra/job_logging: custom
  
batch_id: NC_2025-02-14

test:
  enabled: false
  sample_size: 10

tasks:
  - copy_from_lockers
  - colorchecker
  - raw2dng
  - dng2jpg

file_masks:
  raw_files:
    - .RAW
    - .raw
  ccm_files:
    - .txt

colorchecker:
  height: 9528
  width: 13376
  bpp: 16
  ccm_gamma: 1

raw2dng:
  height: 9528
  width: 13376
  bpp: 16
#  bpp: 12

dng2jpg:
  develop_images: true
  fix_access_rights: true



job_now_date: &nowdir ${now:%Y-%m-%d}
