# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - dng_tags: default
  - override hydra/job_logging: custom
  
batch_id: NC_2025-02-21
tasks:
  # - copy_from_lockers
  # - colorchecker
  - raw2png
  - png2jpg
  # - raw2dng

file_masks:
  raw_files:
    - .RAW
    - .raw
  ccm_files:
    - .txt

raw2dng:
  height: 9528
  width: 13376
  bpp: 16
#  bpp: 12

#raw2dng:
#  height: 9528
#  width: 13376
#  bpp: 16

colorchecker:
  height: 9528
  width: 13376
  bpp: 16
  ccm_gamma: 1

raw2png:
  ccm_name: default

png2jpg:
  profile_name: default
  develop_images: true
  fix_access_rights: true


#copy_from_lockers:
#  raw_extension: .RAW # either .RAW or .ARW
  
job_now_date: &nowdir ${now:%Y-%m-%d}

max_workers: 12
