# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default
  - dng_tags: default
  - exif: default
  - ccm: NC_1740166530
  - batch_ids: test
  - asfm: default
  - date_ranges: default
  - override hydra/job_logging: custom

hydra:
  run:
    dir: ${paths.log_dir}/${season}/${batch_id}/${job_now}
  output_subdir: ${hydra.run.dir}/hydra

job_now: &nowdir ${now:%Y-%m-%d}/${now:%H:%M:%S}

############################################
# Main configuration for the current batch
############################################
batch_id:
bbot_version:
season:
create_issue: true
timestamp: # epoch timestamp for raw2jpg. Anything before this timestamp will be ignored in the batch
run_mode: batch # single or batch
modes:
  # - sync
  # - correct
  # - asfm
  - label
  - deliver
############################################

tasks: # task for each mode
  sync:
    - sync_from_remote # not implemented # TODO: create task list for sync
  correct:
    - raw2jpg # raw2jpg does raw2dng + dng2jpg
    - update_exif
  asfm:
    - autosfm # not implemented # TODO: create task list for autosfm
  label:
    - detect_plants
    - merge_overlapping_bboxes
    - remap_labels
    - assign_species
  deliver:
    - inspect_images # deliver
    - move_data # deliver
    - report  # deliver

inspection:
  inspect: false
  use_lts_images: false  # set true to inspect from LTS

rt_pp3_name: NC_2025-02-21
ccm_name:

file_masks:
  raw_files:
    - .RAW
    - .raw
  dng_files:
    - .DNG
    - .dng
  png_files:
    - .png
    - .PNG
  
raw2jpg:
  jpg_samples: 0
  resize_factor: 0.25
  remove_dngs: true

max_workers: 16


report:
  save2lts: true
  sample_size: 96 # best if this is a multiple of 12
  reviewers:
    github:
      MD: mkutu #map0425 # Nick N of MD
      NC: mkutu #nnotaba # Nick N of MD
      default: mkutu # Matt K

batch_list:
- batch_id: TX_2024-06-10
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-06-06
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-28
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-24
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-20
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-17
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-14
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-10
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-07
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-05-04
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-04-22
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-04-15
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-04-12
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-04-08
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-04-04
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-04-02
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-03-28
  season: summer_weeds_2024
  bbot_version: v2.0
- batch_id: TX_2024-03-26
  season: summer_weeds_2024
  bbot_version: v2.0