workdir: ${hydra:runtime.cwd}  # where the code is executed
log_dir: ${paths.workdir}/logs/
data_dir: ${paths.workdir}/data/
image_development: ${paths.data_dir}/semifield-utils/image_development/

lts_locations:
  - /mnt/research-projects/s/screberg/longterm_images
  - /mnt/research-projects/s/screberg/GROW_DATA
  - /mnt/research-projects/s/screberg/longterm_images2