workdir: ${hydra:runtime.cwd}  # where the code is executed
log_dir: ${paths.workdir}/logs/
data_dir: ${paths.workdir}/data/longterm_images/

lts_locations:
  - /mnt/research-projects/s/screberg/longterm_images
  - /mnt/research-projects/s/screberg/GROW_DATA
  - /mnt/research-projects/s/screberg/longterm_images2