name: Create Failure Report Issue

on:
  repository_dispatch:
    types: [failure-reported]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Update or Create Failure Issue
      env:
        GH_TOKEN: ${{ secrets.REPORT_BOT_PAT }}
        BATCH_ID: ${{ github.event.client_payload.batch_id }}
        ASSIGNEE: ${{ github.event.client_payload.assignee }}
        REPO: ${{ github.repository }}
        GLOBUS_PREFIX: https://m-ae9b45.7ce1a.03c0.data.globus.org/rsstu/users/s/screberg/longterm_images2/semifield-developed-images
        TASK_NAME: ${{ github.event.client_payload.task_name }}
        ERROR_MSG: ${{ github.event.client_payload.error_msg }}
        IS_SUCCESS: "false"
      run: python scripts/update_or_create_issue.py
